routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\LabelController;
use App\Http\Controllers\Admin\UsersConctroller;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\NoticiasConctroller;
use App\Http\Controllers\Admin\OpportunityController;

/**
 * 
 * RUTAS ADMIN
 * 
 */



Route::name('admin.')->middleware('isAdmin')->prefix('admin')->group(function () {
    
    //LOG DE EVENTOS
    Route::get('/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    //DASHBOARD
    Route::get('/', [DashboardController::class, 'home'])->name('home');



    //ETIQUETAS
    Route::get('/etiquetas', [LabelController::class, 'index'])->name('label.index');

    Route::get('/etiquetas/crear', [LabelController::class, 'create'])->name('label.create');

    //edita perfil
    Route::get('/etiquetas/editar-perfiles', [LabelController::class, 'editProfile'])->name('label.profile.edit');

    //editar grupo de etiquetas
    Route::get('/etiquetas/editar/{tag_group_id}', [LabelController::class, 'editGroup'])->name('label.edit');




    //EQUIPO DE TRABAJO
    Route::get('/equipo-de-trabajo', [TeamController::class, 'index'])->name('team.index');

    

    //OPORTUNIDADES ESTÁNDAR
    Route::get('/oportunidades/estandar', [OpportunityController::class, 'standard'])->name('opportunity.standard');
    Route::get('/oportunidades/estandar/crear', [OpportunityController::class, 'standardCreate'])->name('opportunity.standard.create');
    Route::get('/oportunidades/estandar/editar/{opportunity_id}', [OpportunityController::class, 'standardEdit'])->name('opportunity.standard.edit');

    //OPORTUNIDAD LANDING
    Route::get('/oportunidades/landing', [OpportunityController::class, 'landing'])->name('opportunity.landing');
    Route::get('/oportunidades/landing/crear', [OpportunityController::class, 'landingCreate'])->name('opportunity.landing.create');
    Route::get('/oportunidades/landing/editar/{opportunity_id}', [OpportunityController::class, 'landingEdit'])->name('opportunity.landing.edit');

    //OPORTUNIDAD CONTRATACIÓN
    Route::get('/oportunidades/contratacion', [OpportunityController::class, 'hiring'])->name('opportunity.hiring');
    Route::get('/oportunidades/contratacion/crear', [OpportunityController::class, 'hiringCreate'])->name('opportunity.hiring.create');
    Route::get('/oportunidades/contratacion/editar/{opportunity_id}', [OpportunityController::class, 'hiringEdit'])->name('opportunity.hiring.edit');

    //OPORTUNIDAD MULTIOFERTA
    Route::get('/oportunidades/multi-oferta', [OpportunityController::class, 'multioffer'])->name('opportunity.multioffer');
    Route::get('/oportunidades/multi-oferta/crear', [OpportunityController::class, 'multiofferCreate'])->name('opportunity.multioffer.create');
    Route::get('/oportunidades/multi-oferta/editar/{opportunity_id}', [OpportunityController::class, 'multiofferEdit'])->name('opportunity.multioffer.edit');


    //HOME EDIT
    Route::get('/editar-home', [HomeController::class, 'homeEdit'])->name('home.edit');


    //NOTICIAS
    Route::get('/noticias', [NoticiasConctroller::class, 'noticias'])->name('news');
    Route::get('/noticias/crear', [NoticiasConctroller::class, 'create'])->name('news.create');
    Route::get('/noticias/editar/{noticia_id}', [NoticiasConctroller::class, 'edit'])->name('news.edit');

    //USUARIOS
    Route::get('/usuarios', [UsersConctroller::class, 'users'])->name('users');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.login');
});




Route::get('/router-api', function(){
    return response()->json([
        "listado de tipos de oportunidades"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities/type",
            "description"=>"Devuelve listado de tipos de oportunidades",
            "parameters"=>null
        ],
        "listado de oportunidades"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities",
            "description"=>"Devuelve listado de oportunidades",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "lista de oportunidades según el tipo"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities/{type_id}",
            "description"=>"Devuelve lista de oportunidades según el tipo",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidades a listar.'
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Detalles de la oportunidad"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}",
            "description"=>"Devuelve Detalles de la oportunidad",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ]
        ],
        "listado de oportunidade u offertas asociadas a la oport. multioffer"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}/offers",
            "description"=>"Devuelve listado de oportunidade u offertas asociadas a la oport. multioffer",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "listado de noticias asociadas a una oportunidad"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}/news",
            "description"=>"Devuelve listado de noticias asociadas a una oportunidad",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Lista de recursos del Home"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/resources",
            "description"=>"Devuelve un listado de recursos para usar en el home landing",
            "parameters"=>null
        ],
        "listado del equipo de rutan"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/teams/rutan",
            "description"=>"Devuelve listado del equipo de rutan",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)',
                '?areas'=>'Array, filtra los miembros del equipo por el id del área al que pertenece. Ej: ?areas=[1,2,3]'
            ]
        ],
        "Lista de Áreas del equipo de trabajo ruta n"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/teams/areas",
            "description"=>"Devuelve un listado de Áreas del equipo de trabajo ruta n",
            "parameters"=>null
        ],
        "listado de noticias"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/news",
            "description"=>"Devuelve listado de noticias activas",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Detalles de la noticia"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/news/{new_id}",
            "description"=>"Devuelve el Detalles de una noticia",
            "parameters"=>[
                'new_id' => 'Integer, id de la noticia a buscar.',
            ]
        ]
        
    ]);
});

include('auth.php');

include('app.php');

include('admin.php');

resources/views/admin/dashboard.blade.php
@extends('admin.index')

@section('content')
<div class="container">                         

    <h2 class="text-uppercase text-primary text-dashboard">Dashboard</h2>  
    
    <section class="mt-3">
        <a href="#" class="d-flex align-items-center"><h4 class="text-uppercase text-blak-gray me-2">Secciones fijas</h4> <i class="rn-setting-2"></i></a>
        
        <div class="d-flex align-items-center" x-data="{cdx:0}">
            <div class="mt-3 w-75 overflow-hidden me-3" x-ref="sectionsfix">
                <div class="list-sections-fixer ps-1" x-ref="sectionsover">
                @for($i = 1; $i <= 10; $i++)
                    <div class="card-label mb-2 d-flex text-blak-gray align-items-center justify-content-between w-mn-300 me-3 ">
                        <div class="d-flex align-items-center">
                            <div class="icon-label">
                                <i class="rn-portfolio"></i>
                            </div>                    
                            <div class="d-flex flex-column align-items-start">
                                <span class="title-label">Texto sección fija ({{ $i }})</span>
                            </div>
                        </div>
                    </div>
                @endfor
                    <div class="px-1" x-intersect="cdx = -324"></div>
                </div>
            </div>
            <a href="javascript:void(0);" class="btn-icon" @click.prevent="cdx = cdx + 324; $refs.sectionsfix.scrollTo({ left: cdx, behavior: 'smooth' })"><i class="fe-arrow-right"></i></a>
        </div>
    </section>

    <section class="mt-5">
        <h4 class="text-uppercase text-blak-gray">Actividad reciente</h4>
        <div class="row mt-3">
            @forelse ($activities as $activity)
            <div class="col-md-4 ">
                <div class="card-label card-activitic-news mb-2 d-flex text-blak-gray flex-column align-items-start justify-content-between  op-{{  App\Helpers\Helper::opportunityTypeClass($activity['type_id']) }}">
                    <span class="title-label">{{ $activity['title'] }}</span>
                    <div class="d-flex flex-column">
                        <span class="activity-data-text text-{{  App\Helpers\Helper::opportunityTypeClass($activity['type_id']) }}">Oportunidad {{  App\Helpers\Helper::opportunityType($activity['type_id']) }}</span>
                        <span class="activity-data-date">{{ App\Helpers\Helper::diffForHumans($activity['created_at']) }}</span>
                    </div>
                </div>
            </div>
            @empty
                <div class="col-12">
                    <p class="text-center">No hay actividad reciente.</p>
                </div>
            @endforelse
        </div>
    </section>


    <section class="mt-5">
        <h4 class="text-uppercase text-blak-gray">Oportunidades abiertas</h4>
        <div class="row mt-3">
           
            <div class="col-md-3 ">
                <a href="{{ route('admin.opportunity.standard') }}" class="d-block mb-2 text-center oportunity-hover">
                    <div class="d-flex text-blak-gray flex-column align-items-center">
                        <span class="activity-title mb-0 font-20">Estándar</span>
                        <span class="activity-data-number">{{ $count_standar }}</span>
                         
                    </div>
                    <button class="btn-text">Ir <i class="fe-arrow-right"></i></button>
                </a>
            </div>

            <div class="col-md-3 ">
                <a href="{{ route('admin.opportunity.multioffer') }}" class="d-block mb-2 text-center oportunity-hover">
                    <div class="d-flex text-blak-gray flex-column align-items-center">
                        <span class="activity-title mb-0 font-20">Multioferta</span>
                        <span class="activity-data-number">{{ $count_multi }}</span>
                    </div>
                    <button class="btn-text">Ir <i class="fe-arrow-right"></i></button>
                </a>
            </div>

            <div class="col-md-3 ">
                <a href="{{ route('admin.opportunity.landing') }}" class="d-block mb-2 text-center oportunity-hover">
                    <div class="d-flex text-blak-gray flex-column align-items-center">
                        <span class="activity-title mb-0 font-20">Landing</span>
                        <span class="activity-data-number">{{ $count_landing }}</span>
                    </div>
                    <button class="btn-text">Ir <i class="fe-arrow-right"></i></button>
                </a>
            </div>

            <div class="col-md-3 ">
                <a href="{{ route('admin.opportunity.hiring') }}" class="d-block mb-2 text-center oportunity-hover">
                    <div class="d-flex text-blak-gray flex-column align-items-center">
                        <span class="activity-title mb-0 font-20">Contratación</span>
                        <span class="activity-data-number">{{ $count_hiring }}</span>
                    </div>
                    <button class="btn-text">Ir <i class="fe-arrow-right"></i></button>
                </a>
            </div>
        </div>
    </section>
</div> 
@endsection

@push('before-alpinejs')
    <script defer src="https://unpkg.com/@alpinejs/intersect@3.x.x/dist/cdn.min.js"></script>
@endpush

resources/views/admin/footer-script.blade.php
<!-- Vendor js -->
<script src="{{ asset('js/vendor.min.js') }}"></script>

<script src="{{ asset('libs/sweetalert2/sweetalert2.min.js') }}"></script>
@stack('before-scripts')
@yield('before-scripts')
<!-- App js -->
<script src="{{ asset('js/app.js') }}"></script>

<!-- Tost-->
<script defer src="{{ asset('libs/jquery-toast-plugin/jquery.toast.min.js') }}"></script>
<script defer src="{{ asset('libs/jquery-toast-plugin/toastr.init.js') }}"></script>

<script src="{{ asset('js/notification.js') }}"></script>

@yield('scripts')
@stack('scripts')

@livewireScripts

resources/views/admin/head.blade.php
<head>
    <meta charset="utf-8" />
    <title>Ruta N Digital</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="description" />
    <meta content="Ruta N Medellín" name="author" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   
    <link rel="shortcut icon" href="{{asset('image/icon-32x32.png')}}">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,700i,900&display=swap" rel="stylesheet">
    <!-- Jquery Toast css -->
    <link href="{{ asset('libs/jquery-toast-plugin/jquery.toast.min.css') }}" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="{{asset('css/bootstrap.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('css/icons.min.css')}}" rel="stylesheet" type="text/css" />

    @yield('before-styles')
    @stack('before-styles')
    
    <link href="{{asset('css/app.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('libs/sweetalert2/sweetalert2.min.css') }}">
    
    <link href="{{asset('css/animate.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('css/icon-rn.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('css/rutan.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('css/rutan-mobile.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">
    
    @stack('before-alpinejs')
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    
    @yield('styles')
    @stack('styles')

    @livewireStyles

</head>

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
@include('admin.head')


<body class="loading">

    <!-- Begin page -->
    <div id="wrapper">

        

        <!-- ========== Left Sidebar Start ========== -->
        @include('admin.left-menu')
        <!-- Left Sidebar End -->

        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->
        @include('admin.menu-top')
        
        <div class="content-page">
            <!-- Topbar Start -->
            {{-- @include('admin.top-menu') --}}
            <!-- end Topbar -->
            <div class="content">

                <!-- Start Content-->
                @yield('content')
                 <!-- container -->

            </div> <!-- content -->

            <!-- Footer Start -->
            
            <!-- end Footer -->

        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->


    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>

    <!-- script JS -->
    @include('admin.footer-script')

</body>

</html>

resources/views/admin/left-menu.blade.php
<div class="left-side-menu-rutn" x-data="{}">
        
    <button type="button"
        x-on:click="document.querySelector('.left-side-menu-rutn').classList.remove('left-menu-movile-active')"
        class="btn-cloce-left-bar left-bar-toggle waves-effect waves-light"><i class="fe-x"></i></button>
    <div class="logo-box">
        <a href="{{ route('admin.home') }}" class="logo logo-light text-center">
            <span class="logo-lg">
                <img src="{{ asset('image/logo-alt.png') }}" alt="" height="69">
            </span>
        </a>
    </div>
    <hr class="mt-0 mb-2 mb-md-4 bg-transparent">

    <div class="scrollbar-simplebar pb-4" data-simplebar>
        <!--- Sidemenu -->
        <div id="sidebar-menu" >
           
            <ul id="side-menu">
                <li>
                    <a href="{{ route('admin.home') }}" class="option-firts-menu">
                        <i class="rn-dashboard"></i>
                        <h5> Dashboard </h5>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.home.edit') }}" class="option-firts-menu">
                        <i class="rn-home"></i>
                        <h5> editar home </h5>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.team.index') }}" class="option-firts-menu">
                        <i class="rn-team"></i>
                        <h5> Equipo de trabajo </h5>
                    </a>
                </li>

                <li>
                    <a href="#oportunidades-option" class="option-firts-menu" data-bs-toggle="collapse">
                        <i class="rn-portfolio"></i>
                        <h5> oportunidades </h5>
                        <span class="menu-arrow"></span>
                    </a>
                    <div class="collapse" id="oportunidades-option">
                        <ul class="nav-second-level">
                            <li>
                                <a href="{{ route('admin.opportunity.standard') }}">Estándar</a>
                                <a href="{{ route('admin.opportunity.multioffer') }}">Multi oferta</a>
                                <a href="{{ route('admin.opportunity.landing') }}">Landing</a>
                                <a href="{{ route('admin.opportunity.hiring') }}">Contratación</a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li>
                    <a href="{{ route('admin.news') }}" class="option-firts-menu">
                        <i class="rn-noticias"></i>
                        <h5> noticias </h5>
                    </a>
                </li>

                {{-- <li>
                    <a href="#" class="option-firts-menu">
                        <i class="rn-eventos"></i>
                        <h5> Eventos </h5>
                    </a>
                </li>
                <li>
                    <a href="#" class="option-firts-menu">
                        <i class="rn-toolkit"></i>
                        <h5> Toolkit </h5>
                    </a>
                </li> --}}
                <li>
                    <a href="{{ route('admin.users') }}" class="option-firts-menu">
                        <i class="rn-users-setting"></i>
                        <h5> Usuarios </h5>
                    </a>
                </li>
                {{-- <li>
                    <a href="#" class="option-firts-menu">
                        <i class="rn-pqrs"></i>
                        <h5> PQRS </h5>
                    </a>
                </li> --}}
                <li>
                    <a href="{{ route('admin.label.index') }}" class="option-firts-menu">
                        <i class="rn-category"></i>
                        <h5> Etiquetas </h5>
                    </a>
                </li>
                <li>
                    <a href="#" class="option-firts-menu">
                        <i class="rn-setting"></i>
                        <h5> Configuración </h5>
                    </a>
                </li>
            </ul>
        </div>
        
        <!-- End Sidebar -->
        <div class="clearfix"></div>
    </div>
    

    <!-- Sidebar -left -->

</div>

resources/views/admin/menu-top.blade.php
<div class="navbar-rutan-admin">
    <div class="container">
        <div class="d-flex justify-content-end align-items-center">
            <x-admin.dashboard.btn-nuevo/>

            <div class="menu-options ps-2">
                <div class="nav-link nav-user me-0 waves-effect waves-light d-flex flex-column align-items-start justify-content-start " >
                    <a href="#" class="position-relative d-flex flex-column align-items-start justify-content-start">
                        <span class="pro-user-name ms-0 text-uppercase font-18 mb-0 line-height-1 text-brandon"><b>{{ auth()->user()->fullName() }}</b></span>
                        <span class="text-muted line-height-1 ">Editar mi perfil</span>
                    </a>
                    <a href="{{ route('auth.logout') }}" class="text-danger font-18 pt-1"><b>Salir</b></a>
                </div>
            </div>
        </div>
    </div>    
</div>