routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\LabelController;
use App\Http\Controllers\Admin\UsersConctroller;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\NoticiasConctroller;
use App\Http\Controllers\Admin\OpportunityController;

/**
 * 
 * RUTAS ADMIN
 * 
 */



Route::name('admin.')->middleware('isAdmin')->prefix('admin')->group(function () {
    
    //LOG DE EVENTOS
    Route::get('/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    //DASHBOARD
    Route::get('/', [DashboardController::class, 'home'])->name('home');



    //ETIQUETAS
    Route::get('/etiquetas', [LabelController::class, 'index'])->name('label.index');

    Route::get('/etiquetas/crear', [LabelController::class, 'create'])->name('label.create');

    //edita perfil
    Route::get('/etiquetas/editar-perfiles', [LabelController::class, 'editProfile'])->name('label.profile.edit');

    //editar grupo de etiquetas
    Route::get('/etiquetas/editar/{tag_group_id}', [LabelController::class, 'editGroup'])->name('label.edit');




    //EQUIPO DE TRABAJO
    Route::get('/equipo-de-trabajo', [TeamController::class, 'index'])->name('team.index');

    

    //OPORTUNIDADES ESTÁNDAR
    Route::get('/oportunidades/estandar', [OpportunityController::class, 'standard'])->name('opportunity.standard');
    Route::get('/oportunidades/estandar/crear', [OpportunityController::class, 'standardCreate'])->name('opportunity.standard.create');
    Route::get('/oportunidades/estandar/editar/{opportunity_id}', [OpportunityController::class, 'standardEdit'])->name('opportunity.standard.edit');

    //OPORTUNIDAD LANDING
    Route::get('/oportunidades/landing', [OpportunityController::class, 'landing'])->name('opportunity.landing');
    Route::get('/oportunidades/landing/crear', [OpportunityController::class, 'landingCreate'])->name('opportunity.landing.create');
    Route::get('/oportunidades/landing/editar/{opportunity_id}', [OpportunityController::class, 'landingEdit'])->name('opportunity.landing.edit');

    //OPORTUNIDAD CONTRATACIÓN
    Route::get('/oportunidades/contratacion', [OpportunityController::class, 'hiring'])->name('opportunity.hiring');
    Route::get('/oportunidades/contratacion/crear', [OpportunityController::class, 'hiringCreate'])->name('opportunity.hiring.create');
    Route::get('/oportunidades/contratacion/editar/{opportunity_id}', [OpportunityController::class, 'hiringEdit'])->name('opportunity.hiring.edit');

    //OPORTUNIDAD MULTIOFERTA
    Route::get('/oportunidades/multi-oferta', [OpportunityController::class, 'multioffer'])->name('opportunity.multioffer');
    Route::get('/oportunidades/multi-oferta/crear', [OpportunityController::class, 'multiofferCreate'])->name('opportunity.multioffer.create');
    Route::get('/oportunidades/multi-oferta/editar/{opportunity_id}', [OpportunityController::class, 'multiofferEdit'])->name('opportunity.multioffer.edit');


    //HOME EDIT
    Route::get('/editar-home', [HomeController::class, 'homeEdit'])->name('home.edit');


    //NOTICIAS
    Route::get('/noticias', [NoticiasConctroller::class, 'noticias'])->name('news');
    Route::get('/noticias/crear', [NoticiasConctroller::class, 'create'])->name('news.create');
    Route::get('/noticias/editar/{noticia_id}', [NoticiasConctroller::class, 'edit'])->name('news.edit');

    //USUARIOS
    Route::get('/usuarios', [UsersConctroller::class, 'users'])->name('users');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.login');
});




Route::get('/router-api', function(){
    return response()->json([
        "listado de tipos de oportunidades"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities/type",
            "description"=>"Devuelve listado de tipos de oportunidades",
            "parameters"=>null
        ],
        "listado de oportunidades"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities",
            "description"=>"Devuelve listado de oportunidades",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "lista de oportunidades según el tipo"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunities/{type_id}",
            "description"=>"Devuelve lista de oportunidades según el tipo",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidades a listar.'
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Detalles de la oportunidad"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}",
            "description"=>"Devuelve Detalles de la oportunidad",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ]
        ],
        "listado de oportunidade u offertas asociadas a la oport. multioffer"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}/offers",
            "description"=>"Devuelve listado de oportunidade u offertas asociadas a la oport. multioffer",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "listado de noticias asociadas a una oportunidad"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/opportunity/{type_id}/{opportunity_id}/news",
            "description"=>"Devuelve listado de noticias asociadas a una oportunidad",
            "parameters"=>[
                'type_id' => 'Integer, id del tipo de oportunidad.',
                'opportunity_id' => 'Integer, id de la oportunidad a buscar.',
            ],
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Lista de recursos del Home"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/resources",
            "description"=>"Devuelve un listado de recursos para usar en el home landing",
            "parameters"=>null
        ],
        "listado del equipo de rutan"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/teams/rutan",
            "description"=>"Devuelve listado del equipo de rutan",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)',
                '?areas'=>'Array, filtra los miembros del equipo por el id del área al que pertenece. Ej: ?areas=[1,2,3]'
            ]
        ],
        "Lista de Áreas del equipo de trabajo ruta n"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/home/teams/areas",
            "description"=>"Devuelve un listado de Áreas del equipo de trabajo ruta n",
            "parameters"=>null
        ],
        "listado de noticias"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/news",
            "description"=>"Devuelve listado de noticias activas",
            "parameters"=>null,
            "querys"=>[
                '?per_page'=>'Integer, número de resultados a mostrar por página.',
                '?order'=>'String, orden de resultados (asc, desc)',
                '?page'=>'Integer, paginación de resultados (pag actual a mostrar)'
            ]
        ],
        "Detalles de la noticia"=>[
            "method"=>"GET",
            "type"=>"JSON",
            "url"=>url("/")."/api/v1/news/{new_id}",
            "description"=>"Devuelve el Detalles de una noticia",
            "parameters"=>[
                'new_id' => 'Integer, id de la noticia a buscar.',
            ]
        ]
        
    ]);
});

include('auth.php');

include('app.php');

include('admin.php');

app/Http/Controllers/Api/NoticiaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helpers\Helper;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Noticia;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

 /**
    *
    * @OA\Tag(
    *     name="Noticias",
    *     description="API Endpoints de Noticias"
    * )
*/

class NoticiaController extends Controller
{
    
    /**
    * @OA\Get(
    *     path="/news",
    *     summary="listado de noticias",
    *     tags={"Noticias"},
    *     description="Devuelve listado de noticias activas.",
    *     @OA\Parameter(
    *          name="signature",
    *          description="Firma de autenticación de servicio: hash('256', 'llave privada del servicio'.'identificador único del servicio')",
    *          required=true,
    *          in="header",
    *          @OA\Schema(
    *              type="string"
    *          )
    *     ),
    *     @OA\Parameter(
    *          name="uid",
    *          description="identificador único del servicio",
    *          required=true,
    *          in="header",
    *          @OA\Schema(
    *              type="string"
    *          )
    *     ),
    *     @OA\Parameter(
    *          name="order",
    *          description="orden de resultados (asc, desc).",
    *          required=false,
    *          in="query",
    *          @OA\Schema(
    *              type="string",
    *              enum= {"asc", "desc"}
    *          )
    *     ),
    *     @OA\Parameter(
    *          name="per_page",
    *          description="número de resultados a mostrar por página.",
    *          required=false,
    *          in="query",
    *          @OA\Schema(
    *              type="integer"
    *          )
    *      ),
    *      @OA\Parameter(
    *          name="page",
    *          description=" paginación de resultados (pag actual a mostrar).",
    *          required=false,
    *          in="query",
    *          @OA\Schema(
    *              type="integer"
    *          )
    *     ),
    *     @OA\Response(
    *         response=200,
    *         description="Successful operation"
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    * @OA\Get(
    *     path="/news/{new_id}",
    *     summary="Detalles de la noticia",
    *     tags={"Noticias"},
    *     description="Devuelve el Detalles de una noticia.",
    *     @OA\Parameter(
    *          name="signature",
    *          description="Firma de autenticación de servicio: hash('256', 'llave privada del servicio'.'identificador único del servicio')",
    *          required=true,
    *          in="header",
    *          @OA\Schema(
    *              type="string"
    *          )
    *     ),
    *     @OA\Parameter(
    *          name="uid",
    *          description="identificador único del servicio",
    *          required=true,
    *          in="header",
    *          @OA\Schema(
    *              type="string"
    *          )
    *     ),
    *     @OA\Parameter(
    *          name="new_id",
    *          description="Id de la noticia a buscar",
    *          required=true,
    *          in="path",
    *          @OA\Schema(
    *              type="integer"
    *          )
    *      ),
    *     @OA\Response(
    *         response=200,
    *         description="Successful operation"
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */

    //listado de noticias
    public function noticias(Request $request){

        $lg = app()->currentLocale();
        $order = isset($request->order)?$request->order:'desc';
        $order = Str::lower($order);
        $pag = 10;
        if(isset($request->per_page) AND is_numeric($request->per_page)){
            $pag = $request->per_page;
        }

        try{

            $code = Response::HTTP_INTERNAL_SERVER_ERROR;
            $resp = [
                "status"=>false,
                "msg"=>"Se presentó un error, intentalo despues",
                "data"=>null
            ];

            $data = Noticia::with(['categories' =>function($q3) use($lg){
                $q3->where('noticia_labels.type', 'categories')
                ->select('labels.id', 'labels.name_'.$lg.' as name', 'noticia_labels.type');
            }])
            ->where('status_id', 13)
            ->select('id', 'title_'.$lg.' as title', 'summary_'.$lg.' as text', 'image as thumbnail', 'status_id', 'created_at')
            ->orderBy('created_at',$order)
            ->paginate($pag);

            if(isset($request->order)){
                $data->appends(['order' => $order]);
            }
            
            if(isset($request->per_page) AND is_numeric($request->per_page) ){
                $data->appends(['per_page' => $pag]);
            }

            $resp['status'] = true;
            $resp['msg'] = 'Listado de noticias';
            $resp['data'] = $data->total() > 0?$data:null;
            
            
            return response()->json($resp, 200);  

            //return view('welcome',['data'=>$data]);

        }catch(\Exception $err){
            //capturamos cualquier error 
            $code = Response::HTTP_INTERNAL_SERVER_ERROR;
            $resp = [
                "status"=>false,
                "msg"=>$err->getMessage(),
                "data"=>null
            ];
            
            if($err instanceof HttpException){
                $code = $err->getStatusCode();
                $message = Response::$statusTexts[$code];
                $resp["msg"] = $message;                
            }

            return response()->json($resp, $code);            
        } 
    }


    //detalles de la noticia
    public function noticia(Request $request){

        $lg = app()->currentLocale();
        
        
        
        try{

            $code = Response::HTTP_INTERNAL_SERVER_ERROR;
            $resp = [
                "status"=>false,
                "msg"=>"Se presentó un error, intentalo despues",
                "data"=>null
            ];

            $data = Noticia::with(['categories' =>function($q3) use($lg){
                $q3->where('noticia_labels.type', 'categories')
                ->select('labels.id', 'labels.name_'.$lg.' as name', 'noticia_labels.type');
            }])
            ->with(['targets' =>function($q3) use($lg){
                $q3->where('noticia_labels.type', 'targets')
                ->select('labels.id', 'labels.name_'.$lg.' as name', 'noticia_labels.type');
            }])
            ->with(['area' =>function($q3) use($lg){
                $q3->where('noticia_labels.type', 'area')
                ->select('labels.id', 'labels.name_'.$lg.' as name', 'noticia_labels.type');
            }])
            ->where('status_id', 13)
            ->where('id', $request->new_id)
            ->select('id', 'title_'.$lg.' as title', 'summary_'.$lg.' as summary', 'body_'.$lg.' as text', 'image as thumbnail', 'status_id', 'created_at')
            ->first();   


            if(optional($data->text)){
                $data->text = htmlspecialchars_decode($data->text, ENT_QUOTES);
            }

            $resp['status'] = true;
            $resp['msg'] = 'Detalles de la noticia';
            $resp['data'] = $data;
            

            
            
            return response()->json($resp, 200);  

            //return view('welcome',['data'=>$data]);

        }catch(\Exception $err){
            //capturamos cualquier error 
            $code = Response::HTTP_INTERNAL_SERVER_ERROR;
            $resp = [
                "status"=>false,
                "msg"=>$err->getMessage(),
                "data"=>null
            ];
            
            if($err instanceof HttpException){
                $code = $err->getStatusCode();
                $message = Response::$statusTexts[$code];
                $resp["msg"] = $message;                
            }

            return response()->json($resp, $code);            
        } 
    }
}

resources/views/livewire/admin/noticias/noticias.blade.php
<div >
    <div class="row" x-data="{open:@entangle('open')}">
        <div class="col-md-6">
            <div class="tap-opportunities me-1" :class="{ 'active': open }" @click="open=true">
                Publicadas
            </div>
            <div class="tap-opportunities" :class="{ 'active': !open }" @click="open=false">
                Borrador
            </div>
        </div>
        <div class="col-md-6 d-flex justify-content-end">
            <a href="{{ route('admin.news.create') }}" class="btn btn-custom  text-uppercase">NUEVA NOTICIA</a>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4">
            <div class="form-group mb-0">
                <input type="search" wire:model.debounce.400ms="search" class="form-control input-profile " placeholder="Buscar" >
                @error('search')
                    <span class="text-danger w-100 d-block position-lg-absolute">{{ $message }}</span>
                @enderror
            </div>
        </div>
        <div class="col-md-8 d-flex justify-content-end align-items-center">
            <label class="label-rn me-2">Orden: </label>        
            <div class="form-group mb-0">
                <select class="select-rutan" wire:model="order" >
                    <option class="text-muted" value="DESC"  selected >Más nuevo</option>
                    <option class="text-muted" value="ASC"  selected >Más antiguos</option>
                </select>
                <div class="clearfix"></div>
            </div>
        </div>
    
    </div>



    <section class="mt-4">
        <p class="text-muted">{{ $noticias->total() }} resultados</p>

        @if($noticias->total() > 0)
        <div class="row">       
            @foreach($noticias as $i=>$noticia)
            <div class="col-md-12"  wire:key="op-{{ $noticia->id }}">
                <div class="card-label text-truncate">
                    <div class="d-flex text-blak-gray align-items-center justify-content-between text-truncate">
                        <div class="d-flex align-items-center text-truncate">               
                            <div class="d-flex flex-column align-items-start text-truncate">
                                <span class="title-label ">{{ $noticia->title }} <small class="ms-1 text-muted">Creado {{ App\Helpers\Helper::diffForHumans($noticia->created_at) }}</small></span>
                                <span class="desct-label text-truncate d-block ">Autor: {{ $noticia->author->name }} {{ $noticia->author->last_name }}</span>
                            </div>
                        </div>
                        <div class="dropstart" x-data="{show:false}">
                            <div class="d-flex align-items-center">                            
                                <span class="status-{{ ($noticia->status_id == 13 )?'open':'close' }}"><i class="mdi mdi-checkbox-blank-circle"></i>{{ ($noticia->status_id == 13)?'Publicado':'Borrador' }}</span>
                                <a href="javascript:void(0);" x-on:click="show = ! show"  class="btn-more-vertial " >
                                    <i class="fe-more-vertical" x-show="!show" x-transition></i>
                                    <i class="fe-minus" x-show="show" x-transition></i>
                                </a>
                            </div>
                            <div class="dropdown-menu dropdown-alt" x-show="show" x-transition  @click.outside="show = false">
                                <a class="dropdown-item" x-on:click.prevent="$dispatch('showSweetAlertQuestion', { 
                                    title: 'Eliminar noticia',
                                    text:'¿Quieres eliminar está noticia?',
                                    type:'warning',
                                    actionEmit:'deleteNews',
                                    val: {{ $noticia->id }},
                                    });"  href="javascript:void(0);">Eliminar</a>
                                <span class="text-muted px-2">|</span>
                                <a class="dropdown-item px-3" href="{{ route('admin.news.edit', $noticia->id) }}"  class="btn-text-alt">Editar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach

            <div class="col-12">
                {{ $noticias->links() }}
            </div>   
        </div>
        @else
        <div class="row">
            <div class="col-12">
                <p class="my-5 text-muted text-center">No hay resultados.</p>
            </div>
        </div>
        @endif
    </section>
</div>